const express = require('express')
const Controller = require('../controllers/controller')
const router = express.Router()

router.get('/', Controller.home)
router.post('/', Controller.postLogin)
router.get('/register', Controller.register)
router.post('/register', Controller.postRegister)
router.get('/customer/:id', Controller.helloCustomer)
router.get('/customer/:id/menu', Controller.customerMenu)
router.post('/customer/:id/menu/:MenuId', Controller.customerOrder)
router.get('/customer/:id/order', Controller.customerOrderList)
router.get('/admin', Controller.helloAdmin)
router.get('/admin/menu', Controller.restaurantMenu)
router.get('/admin/list', Controller.customerList)
router.get('/admin/order', Controller.orderList)
router.get('/admin/add/menu', Controller.addMenu)
router.post('/admin/add/menu', Controller.addMenu)
router.get('/register/wallet/:id', Controller.postWallet)
router.get('/admin/list/detail/:id', Controller.customerDetail)
router.get('/admin/edit/menu/:id', Controller.addMenu)
router.post('/admin/edit/menu/:id', Controller.addMenu)

router.get('/logout', Controller.logout)

module.exports = router